spring.application.name=complaint

spring.datasource.url=jdbc:postgresql://dpg-d8psr9c8aovs73bi20d0-a:5432/complaint_db_q7an
spring.datasource.username=complaint_user
spring.datasource.password=wCqPVZU9kHhRvakWeX9hipWHvNAr5jFW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}